### ISSUE TITLE
Total installed extension count twice

### ISSUE THREAD

**Issue by gautamsinh** [nitsan-technologies/ns_ext_compatibility#1]
Hii,
While I have check this extension in typo3 8, I found that total installed extension is count twice!!
Please remove line **748 to752** in file ns_ext_compatibility/blob/master/Classes/Controller/nsextcompatibilityController.php

**Comment by nitsan-technologies** [comment]
Hello @gautamsinh

Thank you for the remarks.
Yes, We just noticed this bug while generating the TYPO38 report. Now, we have resolved this bug. You can download the latest updated extension from GIT as well as TER.

Enjoy this great extension :)

Thanks!
