### ISSUE TITLE
Wrong extension key in composer.json

### ISSUE THREAD

**Issue by jensmarquardt** [nitsan-technologies/ns_ext_compatibility#11]
Hi,

I think the extension key in `composer.json` should be renamed to `ns_ext_compatibility`.

https://github.com/nitsan-technologies/ns_ext_compatibility/blob/5b2a87dc55d485671e423baaabf404894fca53b9/composer.json#L40

**Comment by nitsan-technologies** [comment]
Hey @jensmarquardt 

Yup, That was critical.
And, Thanks for pointing out it.

We have updated it at GIT repository. Soon we will update it at TER too.

Cheers!
