### ISSUE TITLE
Exception when calling Backend Module under TYPO3 6.1.7

### ISSUE THREAD

**Issue by loyaruarutoitsu** [nitsan-technologies/ns_ext_compatibility#15]
Under TYPO3 Version 6.1.7 the following exception is thrown:

`Argument "loadJQuery" was not registered.`

I traced this back to the "Default.html" Layout file which has the argument **loadJQuery** using the viewhelper **f:be.container**.

I guess the argument isn't registered at fluid when having the above TYPO3 version.

**Comment by 2701kai** [comment]
Dear loyaruarutoitsu ,
i surmise you forgot to activate the typoscript, section 3.3 on
https://www.nitsan.in/blog/post/t3ext-day-typo3-extensions-compatibility-report/

**Comment by nitsan-technologies** [comment]
Hey @2701kai 

Yes you are right.

Hey, @loyaruarutoitsu have you included extension in your Template(https://i.imgur.com/RAhuOSl.png)?

Once you include it will work as you need. (https://i.imgur.com/8Zctkbh.png)

Let us know if you are still facing an issue.

Thanks!
