### ISSUE TITLE
Compatibility check 

### ISSUE THREAD

**Issue by cnoelker** [nitsan-technologies/ns_ext_compatibility#17]
Hello,
I started the check on an 8.x TYPO3. The result from one of the checked extension is:

Comp. 8.x => Yes
Comp. 9.x => No

The Current Version Dependency of this extension is:
php => '7.0.0-0.0.0'                                                                                                                            typo3 => '8.7.0-9.5.99'

Although the extension clearly states itself as compatible with 9.5.x, the result of the nx_ext_compatibility check is "not compatible". Why?

**Comment by nitsan-technologies** [comment]
Dear @cnoelker 

We appreciate and thanks to raise the ticket with your feedback. Can you please make sure the following?

**Case 1:**
Hope you have already updated with latest extensions repository, Perform this step https://docs.t3terminal.com/en/latest/ExtNsExtCompatibility/Configuration/Index.html#compulsory-update-extension-repository

**Case 2:**
Are you testing that extension from your local-developed extension? Make sure, your extension is available at TER https://extensions.typo3.org/ with the latest version.

If you are still facing an issue, then let us know, we will happily help you :)

Cheers!
Support Team

PS: If you are interested for extra feature of this extension, then checkout PRO-version at https://t3terminal.com/typo3-extension-compatibility-report-pro

**Comment by cnoelker** [comment]
Hello,
for the extension available in TER, I was able to solve the problem by updating the extension repository.
But for my local-developed extensions, the check should have a look at the version in ext_emconf.php .
What I do not understand is that although the setting is always
typo3' => '8.7.13-9.5.99'
Some extensions are displayed as compatible to 9.x, but others are not. How comes?
Claudia

**Comment by nitsan-technologies** [comment]
Dear Claudia,

Thanks for your quick response. Aha, I understood.

Sorry, currently our extension does not check local-developed extensions with a version from ext_emconf.php At the moment, we are only comparing version from TER.

Thanks for your this good feedback, We will finalize internally with our team to create such feature-request for future release :)

Cheers,
Support Team
