### ISSUE TITLE
PHP Runtime Deprecation Notice: Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by duichwer** [nitsan-technologies/ns_ext_compatibility#19]
I receive the following warning in the typo3 Backend:

PHP Runtime Deprecation Notice
Core: Error handler (BE): PHP Runtime Deprecation Notice: Array and string offset access syntax with curly braces is deprecated in `/typo3conf/ext/ns_ext_compatibility/Classes/PHPExcel-1.8/PHPExcel/Shared/String.php line 541`

https://github.com/nitsan-technologies/ns_ext_compatibility/blob/b95f02ca63f3415408c564739da3566066a4112a/Classes/PHPExcel-1.8/PHPExcel/Shared/String.php#L526

Only for this file for several lines: 526, 527, 538, 539, 541, 542

**Comment by nitsan-technologies** [comment]
Hi @duichwer 

Thanks for your feedback.

We have Release 5.0.1, and in this release, we have fixed your mentioned point.

Thank you!
