### ISSUE TITLE
BE module does not work with TYPO3 6.2

### ISSUE THREAD

**Issue by robert-heinig** [nitsan-technologies/ns_ext_compatibility#2]
f:be.container does not have the following arguments in TYPO3 6.2:
- jQueryNamespace
- includeRequireJsModules

If you remove these arguments, you will see the module content, but due to the missing JS not all things do work properly.

**Comment by nitsan-technologies** [comment]
Hey @robert-heinig 

Thanks for using this extension.

To configure this extension you should follow all steps which are listed at below URL.
**URL:** https://www.nitsan.in/blog/post/t3ext-day-typo3-extensions-compatibility-report/

We think that you have missed **step-2.3** _[Include static TypoScript in template]_ (https://prnt.sc/krzba9)
Once you include the extension in the Template than backend error will not generate any more.

Let us know if you are still facing this issue.

Have a great day ahead :)

Thanks!

**Comment by robert-heinig** [comment]
Thank you for the hint - wouldn't expect that an extension of this type requires TS configuration.
