### ISSUE TITLE
Js error and extension detail view doesn't work

### ISSUE THREAD

**Issue by w010** [nitsan-technologies/ns_ext_compatibility#20]
First run and it throws js error: Uncaught Error: Script error for "datatables", needed by: TYPO3/CMS/NsExtCompatibility/Main
and opens empty modal after clicking on extension.
![image](https://user-images.githubusercontent.com/527417/93900527-c88b9780-fcf5-11ea-9d3d-309a45ea5bca.png)
T3: 10.4.6
ext: 5.0.0

**Comment by nitsan-technologies** [comment]
Hi @w010 

Thanks for your feedback.

We have released 5.0.1, and in this release, we have fixed your mentioned issue.

Thank you!
