### ISSUE TITLE
Support to check compatibility for Typo3 11.4 LTS

### ISSUE THREAD

**Issue by marxram** [nitsan-technologies/ns_ext_compatibility#22]
Since Typo3 11 was finally released in October 2021 (https://typo3.org/article/typo3-v11-lts-warp-speed ) it woulb be great to check compatibility with your extension.

Currently (ns_ext_compatibility 5.0.3) it seems not to support this.
![grafik](https://user-images.githubusercontent.com/21262081/147913066-3fc85e9b-bc14-4098-9d9c-744ca1662b52.png)

**Comment by nitsan-technologies** [comment]
Hey @marxram 

Good news! As per your request, we have configured v11 too. We appreciate your time and feedback.

Cheers!
