### ISSUE TITLE
Email Task via CLI - FAILS with ERROR

### ISSUE THREAD

**Issue by xiconluan** [nitsan-technologies/ns_ext_compatibility#8]
Hey there - i have a problem with the class SendExtensionsReportTask

every time the task "TYPO3 Extensions Compatibility Report via Email Notification (ns_ext_compatibility)" are executed via CLI I get the following Error Message : 

> Core: Exception handler (CLI): Uncaught TYPO3 Exception: Class 'TYPO3\CMS\fluid\View\StandaloneView' not found | Error thrown in file /path/to/vendor/typo3/cms/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3956

With manuell execution every things works fine.
Is possible to change the use column from : 

> use TYPO3\CMS\fluid\View\StandaloneView;

to 
> use TYPO3\CMS\Fluid\View\StandaloneView;

Used Version : 1.1.1
TYPO3 8.7.19

Can some confirm this behavior or give me a hint how to fix it?

Best regards

**Comment by robsonrobi** [comment]
I have the same problem. Any Progress here? Would be great.

**Comment by nitsan-technologies** [comment]
Released in 1.1.3 @surphil Thanks for your support by contributing your patch.
